import * as vscode from 'vscode';
import { expandSelectionRange } from './expandRange';
import { runFormatPasses, FormatPassSettings } from './passes';
import { formatRangeWithRoslyn } from './roslynFormat';
import { detectEol } from './textLines';
import { resolveMaxLineLength } from './editorConfig';

export async function formatSelection(editor: vscode.TextEditor): Promise<void> {
  const document = editor.document;
  if (document.languageId !== 'csharp') {
    vscode.window.showInformationMessage('Format Selection only supports C# files.');
    return;
  }

  if (isAutoGenerated(document)) {
    vscode.window.showInformationMessage('Generated C# files are skipped.');
    return;
  }

  const config = vscode.workspace.getConfiguration('dotnetSolutionNavigator.format', document.uri);
  const range = await expandSelectionRange(document, editor.selection, config.get<boolean>('expandToEnclosingMember', true));
  const tabSize = numberSetting(editor.options.tabSize, 4);
  const insertSpaces = booleanSetting(editor.options.insertSpaces, false);
  const configuredWrapColumn = config.get<number>('wrapColumn', 120);
  const wrapColumn = document.uri.scheme === 'file'
    ? (await resolveMaxLineLength(document.uri.fsPath)) ?? configuredWrapColumn
    : configuredWrapColumn;

  const roslynText = await formatRangeWithRoslyn(document, range, {
    tabSize,
    insertSpaces
  });

  const formatted = runFormatPasses(roslynText, readPassSettings(config), {
    eol: detectEol(document.getText()),
    indentUnit: insertSpaces ? ' '.repeat(tabSize) : '\t',
    tabSize,
    fluentChainMinSegments: config.get<number>('fluentChainMinSegments', 2),
    wrapColumn
  });

  if (formatted === document.getText(range)) {
    return;
  }

  const edit = new vscode.WorkspaceEdit();
  edit.replace(document.uri, range, formatted);
  await vscode.workspace.applyEdit(edit);
}

function isAutoGenerated(document: vscode.TextDocument): boolean {
  const lineCount = Math.min(5, document.lineCount);
  for (let i = 0; i < lineCount; i++) {
    if (document.lineAt(i).text.includes('<auto-generated>')) {
      return true;
    }
  }
  return false;
}

function readPassSettings(config: vscode.WorkspaceConfiguration): FormatPassSettings {
  return {
    normalizeIndentWhitespace: config.get<boolean>('normalizeIndentWhitespace', true),
    enableLeadingComma: config.get<boolean>('enableLeadingComma', true),
    enableFluentChainWrap: config.get<boolean>('enableFluentChainWrap', true),
    enableBlankLineRules: config.get<boolean>('enableBlankLineRules', true),
    leadingCommaWrapStyle: config.get<FormatPassSettings['leadingCommaWrapStyle']>('leadingCommaWrapStyle', 'wrapIfLong')
  };
}

function numberSetting(value: string | number | undefined, fallback: number): number {
  return typeof value === 'number' ? value : fallback;
}

function booleanSetting(value: string | boolean | undefined, fallback: boolean): boolean {
  return typeof value === 'boolean' ? value : fallback;
}
