import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import { expandSelectionRange } from './expandRange';
import { runFormatPasses, FormatPassSettings } from './passes';
import { formatRangeWithRoslyn } from './roslynFormat';
import { detectEol } from './textLines';

export async function formatSelection(editor: vscode.TextEditor): Promise<void> {
  const document = editor.document;
  if (document.languageId !== 'csharp') {
    vscode.window.showInformationMessage('Format Selection only supports C# files.');
    return;
  }

  if (isAutoGenerated(document)) {
    vscode.window.showInformationMessage('Generated C# files are skipped.');
    return;
  }

  if (document.uri.scheme === 'file' && !(await hasEditorConfig(document.uri.fsPath))) {
    vscode.window.showWarningMessage('No .editorconfig found above this file. Roslyn may not match the house C# style.');
  }

  const config = vscode.workspace.getConfiguration('dotnetSolutionNavigator.format', document.uri);
  const range = await expandSelectionRange(document, editor.selection, config.get<boolean>('expandToEnclosingMember', true));
  const tabSize = numberSetting(editor.options.tabSize, 4);
  const insertSpaces = booleanSetting(editor.options.insertSpaces, false);

  const roslynText = await formatRangeWithRoslyn(document, range, {
    tabSize,
    insertSpaces
  });

  const formatted = runFormatPasses(roslynText, readPassSettings(config), {
    eol: detectEol(document.getText()),
    indentUnit: insertSpaces ? ' '.repeat(tabSize) : '\t',
    tabSize,
    fluentChainMinSegments: config.get<number>('fluentChainMinSegments', 3)
  });

  if (formatted === document.getText(range)) {
    return;
  }

  const edit = new vscode.WorkspaceEdit();
  edit.replace(document.uri, range, formatted);
  await vscode.workspace.applyEdit(edit);
}

function isAutoGenerated(document: vscode.TextDocument): boolean {
  const lineCount = Math.min(5, document.lineCount);
  for (let i = 0; i < lineCount; i++) {
    if (document.lineAt(i).text.includes('<auto-generated>')) {
      return true;
    }
  }
  return false;
}

async function hasEditorConfig(filePath: string): Promise<boolean> {
  let current = path.dirname(filePath);
  while (true) {
    if (fs.existsSync(path.join(current, '.editorconfig'))) {
      return true;
    }
    const parent = path.dirname(current);
    if (parent === current) {
      return false;
    }
    current = parent;
  }
}

function readPassSettings(config: vscode.WorkspaceConfiguration): FormatPassSettings {
  return {
    normalizeIndentWhitespace: config.get<boolean>('normalizeIndentWhitespace', true),
    enableLeadingComma: config.get<boolean>('enableLeadingComma', true),
    enableFluentChainWrap: config.get<boolean>('enableFluentChainWrap', true),
    enableBlankLineRules: config.get<boolean>('enableBlankLineRules', true)
  };
}

function numberSetting(value: string | number | undefined, fallback: number): number {
  return typeof value === 'number' ? value : fallback;
}

function booleanSetting(value: string | boolean | undefined, fallback: boolean): boolean {
  return typeof value === 'boolean' ? value : fallback;
}
