import * as assert from 'assert';
import { describe, it } from 'node:test';
import {
  parseRawClassesFromCSharp,
  parsePropertiesFromBody,
  parseFluentConfigurations,
  parseDbContextDbSets,
  parseModelSnapshotFromCSharp,
  buildDbContextScopedModel,
  buildRelationships
} from '../ef/diagram/efDiagramScanner';
import * as os from 'os';
import * as fs from 'fs';
import * as path from 'path';
import {
  saveDiagramToFile,
  loadDiagramFromFile,
  deleteDiagramFile,
  listSavedDiagrams,
  liveSyncDiagramWithCode
} from '../ef/diagram/efDiagramStorage';
import { DiagramFile, EntityModel } from '../ef/diagram/efDiagramModel';

describe('EF Core Diagram Scanner & Storage (Precise PK/FK Detection Engine)', () => {
  it('parseModelSnapshotFromCSharp extracts exact FK from HasForeignKey and leaves ManagerId as non-FK', () => {
    const snapshotCode = `
      // <auto-generated />
      using System;
      using ELDesk.CustomApp.Infrastructure.DbContexts;
      using Microsoft.EntityFrameworkCore;
      using Microsoft.EntityFrameworkCore.Infrastructure;

      namespace ELDesk.CustomApp.SharedInfrastructure.Migrations
      {
          [DbContext(typeof(CustomAppDbContext))]
          partial class CustomAppDbContextModelSnapshot : ModelSnapshot
          {
              protected override void BuildModel(ModelBuilder modelBuilder)
              {
                  modelBuilder.Entity("ELDesk.CustomApp.SharedDomain.Entities.Applications.Entities.Application", b =>
                  {
                      b.Property<int>("Id")
                          .ValueGeneratedOnAdd()
                          .HasColumnType("integer");

                      b.Property<string>("Name")
                          .IsRequired()
                          .HasColumnType("text");

                      b.Property<int?>("ManagerId")
                          .HasColumnType("integer");

                      b.HasKey("Id");

                      b.ToTable("application", (string)null);
                  });

                  modelBuilder.Entity("ELDesk.CustomApp.SharedDomain.Entities.Applications.Entities.ActionCommands.ActionCommandSetting", b =>
                  {
                      b.Property<int>("Id")
                          .ValueGeneratedOnAdd()
                          .HasColumnType("integer");

                      b.Property<int>("AppId")
                          .HasColumnType("integer");

                      b.Property<string>("Name")
                          .IsRequired()
                          .HasColumnType("text");

                      b.HasKey("Id");

                      b.ToTable("actioncommandsetting", (string)null);
                  });

                  modelBuilder.Entity("ELDesk.CustomApp.SharedDomain.Entities.Applications.Entities.ActionCommands.ActionCommandSetting", b =>
                  {
                      b.HasOne("ELDesk.CustomApp.SharedDomain.Entities.Applications.Entities.Application", "Application")
                          .WithMany("ActionCommandSettings")
                          .HasForeignKey("AppId")
                          .OnDelete(DeleteBehavior.Cascade)
                          .IsRequired();
                  });
              }
          }
      }
    `;

    const result = parseModelSnapshotFromCSharp(snapshotCode, '/src/CustomAppDbContextModelSnapshot.cs');
    assert.ok(result);
    assert.equal(result?.dbContextName, 'CustomAppDbContext');

    const app = result?.entities.find(e => e.shortName === 'Application');
    assert.ok(app);
    const managerIdProp = app?.properties.find(p => p.name === 'ManagerId');
    assert.ok(managerIdProp);
    assert.equal(managerIdProp?.isForeignKey, false, 'ManagerId without HasForeignKey must NOT be marked as FK');

    const actionCmd = result?.entities.find(e => e.shortName === 'ActionCommandSetting');
    assert.ok(actionCmd);
    const appIdProp = actionCmd?.properties.find(p => p.name === 'AppId');
    assert.ok(appIdProp);
    assert.equal(appIdProp?.isForeignKey, true, 'AppId must be marked as FK');
    assert.equal(appIdProp?.foreignKeyTargetEntity, 'Application', 'AppId must target Application');

    // Test rich relationship metadata extraction
    const rel = actionCmd?.relationships.find(r => r.toProperty === 'AppId');
    assert.ok(rel);
    assert.equal(rel?.deleteBehavior, 'Cascade');
    assert.equal(rel?.isRequired, true);
    assert.equal(rel?.cardinality, 'one-to-many');
    assert.equal(rel?.navigationName, 'Application');
    assert.equal(rel?.inverseNavigationName, 'ActionCommandSettings');
  });

  it('parsePropertiesFromBody pairs FK with navigation property and leaves scalar ManagerId as non-FK', () => {
    const classBody = `
      [Key]
      public int Id { get; set; }
      public int AppId { get; set; }
      public int? ManagerId { get; set; }
      public virtual Application Application { get; set; }
    `;

    const props = parsePropertiesFromBody(classBody, 'ActionCommandSetting');
    const idProp = props.find(p => p.name === 'Id');
    assert.equal(idProp?.isPrimaryKey, true);

    const appIdProp = props.find(p => p.name === 'AppId');
    assert.equal(appIdProp?.isForeignKey, true);
    assert.equal(appIdProp?.foreignKeyTargetEntity, 'Application');

    const managerIdProp = props.find(p => p.name === 'ManagerId');
    assert.equal(managerIdProp?.isForeignKey, false, 'ManagerId without matching navigation must NOT be an FK');
  });

  it('buildDbContextScopedModel isolates entities and relationships', () => {
    const rawClasses = [
      ...parseRawClassesFromCSharp(
        `public class Application : Entity<int> { public string Name { get; set; } }`,
        '/src/Application.cs',
        'ELDesk.CustomApp'
      ),
      ...parseRawClassesFromCSharp(
        `public class CustomAppDbContext : DbContext { public virtual DbSet<Application> Applications { get; set; } }`,
        '/src/CustomAppDbContext.cs',
        'ELDesk.CustomApp'
      )
    ];

    const dbContextSets = [
      { dbContextName: 'CustomAppDbContext', entityTypes: ['Application'] }
    ];

    const model = buildDbContextScopedModel(rawClasses, [], dbContextSets, []);
    assert.deepEqual(model.availableDbContexts, ['CustomAppDbContext']);
  });

  it('liveSyncDiagramWithCode preserves coordinates and prunes removed entities', () => {
    const saved: DiagramFile = {
      version: 1,
      name: 'Custom',
      createdAt: 100,
      updatedAt: 200,
      entities: {
        Application: { x: 120, y: 150 },
        DeletedOldEntity: { x: 500, y: 500 }
      },
      notes: [
        { id: 'note-1', x: 200, y: 300, text: 'Custom note', color: 'emerald' }
      ]
    };

    const currentEntities: EntityModel[] = [
      {
        id: '1',
        name: 'Application',
        filePath: '/src/Application.cs',
        line: 1,
        projectName: 'App',
        properties: []
      }
    ];

    const synced = liveSyncDiagramWithCode(saved, currentEntities);
    assert.deepEqual(synced, {
      Application: { x: 120, y: 150 }
    });
    assert.equal(saved.notes?.length, 1);
    assert.equal(saved.notes?.[0].color, 'emerald');
  });

  it('diagram storage lifecycle saves, loads, lists, and deletes diagram files', async () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'dotnav-diagram-test-'));
    try {
      const positions = {
        Application: { x: 100, y: 200 },
        User: { x: 400, y: 200 }
      };
      const notes = [
        { id: 'note-1', x: 50, y: 50, text: 'Architecture notes', color: 'blue' }
      ];

      // Save
      const savedOk = await saveDiagramToFile('Overview', positions, tmpDir, undefined, notes);
      assert.equal(savedOk, true);

      // List
      const list = await listSavedDiagrams(tmpDir);
      assert.ok(list.includes('Overview'));

      // Load
      const loaded = await loadDiagramFromFile('Overview', tmpDir);
      assert.ok(loaded);
      assert.equal(loaded?.name, 'Overview');
      assert.deepEqual(loaded?.entities, positions);
      assert.equal(loaded?.notes?.length, 1);
      assert.equal(loaded?.notes?.[0].text, 'Architecture notes');

      // Delete
      const deletedOk = await deleteDiagramFile('Overview', tmpDir);
      assert.equal(deletedOk, true);

      const afterDeleteList = await listSavedDiagrams(tmpDir);
      assert.equal(afterDeleteList.includes('Overview'), false);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it('extracts HasColumnName and HasColumnType from multi-line snapshot chains', () => {
    const snapshotCode = `
      modelBuilder.Entity("MyApp.Domain.Order", b =>
      {
          b.Property<int>("Id")
              .ValueGeneratedOnAdd()
              .HasColumnType("int")
              .HasColumnName("order_id");

          b.Property<string>("CustomerCode")
              .IsRequired()
              .HasMaxLength(50)
              .HasColumnType("varchar(50)")
              .HasColumnName("cust_code");

          b.Property<decimal>("TotalAmount")
              .HasColumnType("decimal(18,2)")
              .HasColumnName("total_amt");

          b.HasKey("Id");
          b.ToTable("orders", "sales");
      });
    `;

    const result = parseModelSnapshotFromCSharp(
      `[DbContext(typeof(AppDbContext))] partial class AppDbContextModelSnapshot : ModelSnapshot { protected override void BuildModel(ModelBuilder modelBuilder) { ${snapshotCode} } }`,
      '/src/AppDbContextModelSnapshot.cs'
    );

    assert.ok(result);
    const order = result?.entities.find(e => e.shortName === 'Order');
    assert.ok(order);
    assert.equal(order?.tableName, 'orders');
    assert.equal(order?.schemaName, 'sales');

    const idProp = order?.properties.find(p => p.name === 'Id');
    assert.equal(idProp?.columnName, 'order_id');
    assert.equal(idProp?.columnType, 'int');

    const custProp = order?.properties.find(p => p.name === 'CustomerCode');
    assert.equal(custProp?.columnName, 'cust_code');
    assert.equal(custProp?.columnType, 'varchar(50)');

    const totalProp = order?.properties.find(p => p.name === 'TotalAmount');
    assert.equal(totalProp?.columnName, 'total_amt');
    assert.equal(totalProp?.columnType, 'decimal(18,2)');
  });

  it('parsePropertiesFromBody extracts [Column] attribute and infers SQL types', () => {
    const classBody = `
      [Key]
      public int Id { get; set; }

      [Column("user_name", TypeName = "varchar(100)")]
      public string UserName { get; set; }

      [Column("created_at")]
      public DateTime CreatedAt { get; set; }
    `;

    const props = parsePropertiesFromBody(classBody, 'UserProfile');
    const userProp = props.find(p => p.name === 'UserName');
    assert.equal(userProp?.columnName, 'user_name');
    assert.equal(userProp?.columnType, 'varchar(100)');

    const createdProp = props.find(p => p.name === 'CreatedAt');
    assert.equal(createdProp?.columnName, 'created_at');
    assert.equal(createdProp?.columnType, 'datetime2');
  });

  it('buildDbContextScopedModel performs hybrid reconciliation: adds unmigrated entities and appends new C# properties', () => {
    // 1. Snapshot has migrated entity 'Category' with 1 property
    const snapshot: any = {
      dbContextName: 'AppDbContext',
      filePath: '/src/Snapshot.cs',
      entities: [
        {
          fullName: 'MyApp.Category',
          shortName: 'Category',
          tableName: 'categories',
          primaryKeys: ['Id'],
          properties: [
            { name: 'Id', type: 'int', isPrimaryKey: true, isForeignKey: false, isNullable: false, isNavigation: false, columnName: 'id', columnType: 'int' }
          ],
          relationships: []
        }
      ]
    };

    // 2. Live C# classes have:
    // - Category with NEW property 'Description'
    // - Product (new entity with DbSet, not yet in Snapshot!)
    const rawClasses = [
      ...parseRawClassesFromCSharp(
        `public class Category { public int Id { get; set; } public string Description { get; set; } }`,
        '/src/Category.cs',
        'App'
      ),
      ...parseRawClassesFromCSharp(
        `public class Product { public int Id { get; set; } public int CategoryId { get; set; } }`,
        '/src/Product.cs',
        'App'
      )
    ];

    const dbContextSets = [
      { dbContextName: 'AppDbContext', entityTypes: ['Category', 'Product'] }
    ];

    const model = buildDbContextScopedModel(rawClasses, [], dbContextSets, [snapshot]);
    assert.deepEqual(model.availableDbContexts, ['AppDbContext']);

    const entities = model.entitiesByContext['AppDbContext'];
    assert.equal(entities.length, 2, 'Should reconcile 2 entities (1 migrated + 1 unmigrated)');

    const cat = entities.find(e => e.name === 'Category');
    assert.ok(cat);
    const descProp = cat?.properties.find(p => p.name === 'Description');
    assert.ok(descProp, 'Should append unmigrated Description property to Category');
    assert.equal(descProp?.isUnmigrated, true);

    const prod = entities.find(e => e.name === 'Product');
    assert.ok(prod, 'Should discover unmigrated Product entity');
    assert.equal(prod?.isUnmigrated, true);
  });

  it('preserves all snapshot entities even if they do not have direct DbSet properties in DbContext (e.g. ActionCommandSetting)', () => {
    const snapshot: any = {
      dbContextName: 'CustomAppSharedDbContext',
      filePath: '/src/Snapshot.cs',
      entities: [
        {
          fullName: 'ELDesk.CustomApp.SharedDomain.Entities.ActionCommandSetting',
          shortName: 'ActionCommandSetting',
          tableName: 'actioncommandsetting',
          primaryKeys: ['Id'],
          properties: [
            { name: 'Id', type: 'int', isPrimaryKey: true, isForeignKey: false, isNullable: false, isNavigation: false, columnName: 'id', columnType: 'int' }
          ],
          relationships: []
        },
        {
          fullName: 'ELDesk.CustomApp.SharedDomain.Entities.ActionCommandMappingSetting',
          shortName: 'ActionCommandMappingSetting',
          tableName: 'actioncommandmappingsetting',
          primaryKeys: ['Id'],
          properties: [
            { name: 'Id', type: 'int', isPrimaryKey: true, isForeignKey: false, isNullable: false, isNavigation: false, columnName: 'id', columnType: 'int' }
          ],
          relationships: []
        }
      ]
    };

    // DbContext only lists Application in DbSet, but snapshot has ActionCommandSetting and ActionCommandMappingSetting
    const dbContextSets = [
      { dbContextName: 'CustomAppSharedDbContext', entityTypes: ['Application'] }
    ];

    const rawClasses = [
      ...parseRawClassesFromCSharp(
        `public class Application { public int Id { get; set; } }`,
        '/src/Application.cs',
        'App'
      )
    ];

    const model = buildDbContextScopedModel(rawClasses, [], dbContextSets, [snapshot]);
    const entities = model.entitiesByContext['CustomAppSharedDbContext'];

    assert.ok(entities.some(e => e.name === 'ActionCommandSetting'), 'ActionCommandSetting MUST be preserved from snapshot');
    assert.ok(entities.some(e => e.name === 'ActionCommandMappingSetting'), 'ActionCommandMappingSetting MUST be preserved from snapshot');
    assert.ok(entities.some(e => e.name === 'Application'), 'Application (unmigrated) MUST be included');
    assert.equal(entities.length, 3);
  });
});
