import * as assert from 'assert';
import { describe, it } from 'node:test';
import {
  parseRawClassesFromCSharp,
  parseFluentConfigurations,
  parseDbContextDbSets,
  parseModelSnapshotFromCSharp,
  buildDbContextScopedModel,
  buildRelationships
} from '../ef/diagram/efDiagramScanner';
import { liveSyncDiagramWithCode } from '../ef/diagram/efDiagramStorage';
import { DiagramFile, EntityModel } from '../ef/diagram/efDiagramModel';

describe('EF Core Diagram Scanner & Storage (DbContext-Centric Migration-Style)', () => {
  it('parseModelSnapshotFromCSharp extracts tables, properties, PK, FK, and schema directly from EF Core snapshot', () => {
    const snapshotCode = `
      // <auto-generated />
      using System;
      using ELDesk.CustomApp.Infrastructure.DbContexts;
      using Microsoft.EntityFrameworkCore;
      using Microsoft.EntityFrameworkCore.Infrastructure;

      namespace ELDesk.CustomApp.SharedInfrastructure.Migrations
      {
          [DbContext(typeof(CustomAppDbContext))]
          partial class CustomAppDbContextModelSnapshot : ModelSnapshot
          {
              protected override void BuildModel(ModelBuilder modelBuilder)
              {
                  modelBuilder.Entity("ELDesk.CustomApp.SharedDomain.Entities.Applications.Entities.AppField", b =>
                  {
                      b.Property<int>("Id")
                          .ValueGeneratedOnAdd()
                          .HasColumnType("integer");

                      b.Property<string>("Name")
                          .IsRequired()
                          .HasColumnType("text");

                      b.Property<int>("TenantId")
                          .HasColumnType("integer");

                      b.Property<int>("FormId")
                          .HasColumnType("integer");

                      b.HasKey("Id");

                      b.ToTable("formelement", "custom");

                      b.HasOne("ELDesk.CustomApp.SharedDomain.Entities.Applications.Entities.SubmitForms.Form", "Form")
                          .WithMany("FormElements")
                          .HasForeignKey("FormId");
                  });

                  modelBuilder.Entity("ELDesk.CustomApp.SharedDomain.Entities.Applications.Entities.SubmitForms.Form", b =>
                  {
                      b.Property<int>("Id")
                          .ValueGeneratedOnAdd()
                          .HasColumnType("integer");

                      b.Property<string>("Title")
                          .HasColumnType("text");

                      b.HasKey("Id");

                      b.ToTable("form", "custom");
                  });
              }
          }
      }
    `;

    const result = parseModelSnapshotFromCSharp(snapshotCode, '/src/CustomAppDbContextModelSnapshot.cs');
    assert.ok(result);
    assert.equal(result?.dbContextName, 'CustomAppDbContext');
    assert.equal(result?.entities.length, 2);

    const appField = result?.entities.find(e => e.shortName === 'AppField');
    assert.ok(appField);
    assert.equal(appField?.tableName, 'formelement');
    assert.equal(appField?.schemaName, 'custom');
    assert.deepEqual(appField?.primaryKeys, ['Id']);

    const formIdProp = appField?.properties.find(p => p.name === 'FormId');
    assert.ok(formIdProp);
    assert.equal(formIdProp?.isForeignKey, true);
    assert.equal(formIdProp?.foreignKeyTargetEntity, 'Form');

    assert.equal(appField?.relationships.length, 1);
    assert.equal(appField?.relationships[0].fromEntity, 'Form');
    assert.equal(appField?.relationships[0].toEntity, 'AppField');
  });

  it('buildDbContextScopedModel isolates entities per DbContext and resolves inheritance hierarchy', () => {
    const rawClasses = [
      // Base classes
      ...parseRawClassesFromCSharp(
        `public class Entity<TKey> { public TKey Id { get; set; } }`,
        '/src/Entity.cs',
        'ELDesk.Shared.Domain'
      ),
      ...parseRawClassesFromCSharp(
        `public class TenantEntity : Entity<int> { public int TenantId { get; set; } }`,
        '/src/TenantEntity.cs',
        'ELDesk.Shared.Domain'
      ),
      // DbContext hierarchy: CustomAppDbContext -> CustomAppSharedDbContext
      ...parseRawClassesFromCSharp(
        `public class CustomAppSharedDbContext : DbContext { public virtual DbSet<Form> Forms { get; set; } }`,
        '/src/CustomAppSharedDbContext.cs',
        'ELDesk.CustomApp'
      ),
      ...parseRawClassesFromCSharp(
        `public class CustomAppDbContext : CustomAppSharedDbContext { public virtual DbSet<AppField> Fields { get; set; } }`,
        '/src/CustomAppDbContext.cs',
        'ELDesk.CustomApp'
      ),
      // Identity DbContext
      ...parseRawClassesFromCSharp(
        `public class IdentityContext : DbContext { public virtual DbSet<Tenant> Tenants { get; set; } }`,
        '/src/IdentityContext.cs',
        'ELDesk.IAM'
      ),
      // Entities
      ...parseRawClassesFromCSharp(
        `public class Form : TenantEntity { public string Title { get; set; } }`,
        '/src/Form.cs',
        'ELDesk.CustomApp'
      ),
      ...parseRawClassesFromCSharp(
        `public class AppField : TenantEntity { public int FormId { get; set; } }`,
        '/src/AppField.cs',
        'ELDesk.CustomApp'
      ),
      ...parseRawClassesFromCSharp(
        `public class Tenant : Entity<int> { public string Name { get; set; } }`,
        '/src/Tenant.cs',
        'ELDesk.IAM'
      )
    ];

    const dbContextSets = [
      { dbContextName: 'CustomAppSharedDbContext', entityTypes: ['Form'] },
      { dbContextName: 'CustomAppDbContext', entityTypes: ['AppField'] },
      { dbContextName: 'IdentityContext', entityTypes: ['Tenant'] }
    ];

    const model = buildDbContextScopedModel(rawClasses, [], dbContextSets, []);
    assert.ok(model.availableDbContexts.includes('CustomAppDbContext'));
    assert.ok(model.availableDbContexts.includes('IdentityContext'));

    // CustomAppDbContext must inherit Form from CustomAppSharedDbContext AND have AppField
    const customAppEntities = model.entitiesByContext['CustomAppDbContext'] || [];
    const customAppNames = customAppEntities.map(e => e.name);
    assert.ok(customAppNames.includes('Form'), 'CustomAppDbContext must inherit Form');
    assert.ok(customAppNames.includes('AppField'), 'CustomAppDbContext must have AppField');
    assert.ok(!customAppNames.includes('Tenant'), 'CustomAppDbContext must NOT contain Tenant from IdentityContext');

    // IdentityContext must only contain Tenant
    const identityEntities = model.entitiesByContext['IdentityContext'] || [];
    const identityNames = identityEntities.map(e => e.name);
    assert.ok(identityNames.includes('Tenant'), 'IdentityContext must have Tenant');
    assert.ok(!identityNames.includes('Form'), 'IdentityContext must NOT contain Form');
  });

  it('buildRelationships discovers relationships from navigation & FK properties', () => {
    const entities: EntityModel[] = [
      {
        id: '1',
        name: 'Form',
        filePath: '/src/Form.cs',
        line: 1,
        projectName: 'App',
        properties: [
          { name: 'Id', type: 'int', isPrimaryKey: true, isForeignKey: false, isNullable: false, isNavigation: false },
          { name: 'Fields', type: 'ICollection<AppField>', isPrimaryKey: false, isForeignKey: false, isNullable: false, isNavigation: true, isCollectionNavigation: true, navigationTargetEntity: 'AppField' }
        ]
      },
      {
        id: '2',
        name: 'AppField',
        filePath: '/src/AppField.cs',
        line: 1,
        projectName: 'App',
        properties: [
          { name: 'Id', type: 'int', isPrimaryKey: true, isForeignKey: false, isNullable: false, isNavigation: false },
          { name: 'FormId', type: 'int', isPrimaryKey: false, isForeignKey: true, isNullable: false, isNavigation: false, foreignKeyTargetEntity: 'Form' }
        ]
      }
    ];

    const rels = buildRelationships(entities);
    assert.ok(rels.length > 0);
    const formToField = rels.find(r => r.fromEntity === 'Form' && r.toEntity === 'AppField');
    assert.ok(formToField);
    assert.equal(formToField?.cardinality, 'one-to-many');
  });

  it('liveSyncDiagramWithCode preserves coordinates and prunes removed entities', () => {
    const saved: DiagramFile = {
      version: 1,
      name: 'Custom',
      createdAt: 100,
      updatedAt: 200,
      entities: {
        Form: { x: 120, y: 150 },
        DeletedOldEntity: { x: 500, y: 500 }
      }
    };

    const currentEntities: EntityModel[] = [
      {
        id: '1',
        name: 'Form',
        filePath: '/src/Form.cs',
        line: 1,
        projectName: 'App',
        properties: []
      }
    ];

    const synced = liveSyncDiagramWithCode(saved, currentEntities);
    assert.deepEqual(synced, {
      Form: { x: 120, y: 150 }
    });
  });
});
