import * as assert from 'assert';
import { describe, it } from 'node:test';
import {
  parseRawClassesFromCSharp,
  parsePropertiesFromBody,
  parseFluentConfigurations,
  parseDbContextDbSets,
  parseModelSnapshotFromCSharp,
  buildDbContextScopedModel,
  buildRelationships
} from '../ef/diagram/efDiagramScanner';
import { liveSyncDiagramWithCode } from '../ef/diagram/efDiagramStorage';
import { DiagramFile, EntityModel } from '../ef/diagram/efDiagramModel';

describe('EF Core Diagram Scanner & Storage (Precise PK/FK Detection Engine)', () => {
  it('parseModelSnapshotFromCSharp extracts exact FK from HasForeignKey and leaves ManagerId as non-FK', () => {
    const snapshotCode = `
      // <auto-generated />
      using System;
      using ELDesk.CustomApp.Infrastructure.DbContexts;
      using Microsoft.EntityFrameworkCore;
      using Microsoft.EntityFrameworkCore.Infrastructure;

      namespace ELDesk.CustomApp.SharedInfrastructure.Migrations
      {
          [DbContext(typeof(CustomAppDbContext))]
          partial class CustomAppDbContextModelSnapshot : ModelSnapshot
          {
              protected override void BuildModel(ModelBuilder modelBuilder)
              {
                  modelBuilder.Entity("ELDesk.CustomApp.SharedDomain.Entities.Applications.Entities.Application", b =>
                  {
                      b.Property<int>("Id")
                          .ValueGeneratedOnAdd()
                          .HasColumnType("integer");

                      b.Property<string>("Name")
                          .IsRequired()
                          .HasColumnType("text");

                      b.Property<int?>("ManagerId")
                          .HasColumnType("integer");

                      b.HasKey("Id");

                      b.ToTable("application", (string)null);
                  });

                  modelBuilder.Entity("ELDesk.CustomApp.SharedDomain.Entities.Applications.Entities.ActionCommands.ActionCommandSetting", b =>
                  {
                      b.Property<int>("Id")
                          .ValueGeneratedOnAdd()
                          .HasColumnType("integer");

                      b.Property<int>("AppId")
                          .HasColumnType("integer");

                      b.Property<string>("Name")
                          .IsRequired()
                          .HasColumnType("text");

                      b.HasKey("Id");

                      b.ToTable("actioncommandsetting", (string)null);
                  });

                  modelBuilder.Entity("ELDesk.CustomApp.SharedDomain.Entities.Applications.Entities.ActionCommands.ActionCommandSetting", b =>
                  {
                      b.HasOne("ELDesk.CustomApp.SharedDomain.Entities.Applications.Entities.Application", "Application")
                          .WithMany("ActionCommandSettings")
                          .HasForeignKey("AppId")
                          .OnDelete(DeleteBehavior.Cascade)
                          .IsRequired();
                  });
              }
          }
      }
    `;

    const result = parseModelSnapshotFromCSharp(snapshotCode, '/src/CustomAppDbContextModelSnapshot.cs');
    assert.ok(result);
    assert.equal(result?.dbContextName, 'CustomAppDbContext');

    const app = result?.entities.find(e => e.shortName === 'Application');
    assert.ok(app);
    const managerIdProp = app?.properties.find(p => p.name === 'ManagerId');
    assert.ok(managerIdProp);
    assert.equal(managerIdProp?.isForeignKey, false, 'ManagerId without HasForeignKey must NOT be marked as FK');

    const actionCmd = result?.entities.find(e => e.shortName === 'ActionCommandSetting');
    assert.ok(actionCmd);
    const appIdProp = actionCmd?.properties.find(p => p.name === 'AppId');
    assert.ok(appIdProp);
    assert.equal(appIdProp?.isForeignKey, true, 'AppId must be marked as FK');
    assert.equal(appIdProp?.foreignKeyTargetEntity, 'Application', 'AppId must target Application');

    // Test rich relationship metadata extraction
    const rel = actionCmd?.relationships.find(r => r.toProperty === 'AppId');
    assert.ok(rel);
    assert.equal(rel?.deleteBehavior, 'Cascade');
    assert.equal(rel?.isRequired, true);
    assert.equal(rel?.cardinality, 'one-to-many');
    assert.equal(rel?.navigationName, 'Application');
    assert.equal(rel?.inverseNavigationName, 'ActionCommandSettings');
  });

  it('parsePropertiesFromBody pairs FK with navigation property and leaves scalar ManagerId as non-FK', () => {
    const classBody = `
      [Key]
      public int Id { get; set; }
      public int AppId { get; set; }
      public int? ManagerId { get; set; }
      public virtual Application Application { get; set; }
    `;

    const props = parsePropertiesFromBody(classBody, 'ActionCommandSetting');
    const idProp = props.find(p => p.name === 'Id');
    assert.equal(idProp?.isPrimaryKey, true);

    const appIdProp = props.find(p => p.name === 'AppId');
    assert.equal(appIdProp?.isForeignKey, true);
    assert.equal(appIdProp?.foreignKeyTargetEntity, 'Application');

    const managerIdProp = props.find(p => p.name === 'ManagerId');
    assert.equal(managerIdProp?.isForeignKey, false, 'ManagerId without matching navigation must NOT be an FK');
  });

  it('buildDbContextScopedModel isolates entities and relationships', () => {
    const rawClasses = [
      ...parseRawClassesFromCSharp(
        `public class Application : Entity<int> { public string Name { get; set; } }`,
        '/src/Application.cs',
        'ELDesk.CustomApp'
      ),
      ...parseRawClassesFromCSharp(
        `public class CustomAppDbContext : DbContext { public virtual DbSet<Application> Applications { get; set; } }`,
        '/src/CustomAppDbContext.cs',
        'ELDesk.CustomApp'
      )
    ];

    const dbContextSets = [
      { dbContextName: 'CustomAppDbContext', entityTypes: ['Application'] }
    ];

    const model = buildDbContextScopedModel(rawClasses, [], dbContextSets, []);
    assert.deepEqual(model.availableDbContexts, ['CustomAppDbContext']);
  });

  it('liveSyncDiagramWithCode preserves coordinates and prunes removed entities', () => {
    const saved: DiagramFile = {
      version: 1,
      name: 'Custom',
      createdAt: 100,
      updatedAt: 200,
      entities: {
        Application: { x: 120, y: 150 },
        DeletedOldEntity: { x: 500, y: 500 }
      },
      notes: [
        { id: 'note-1', x: 200, y: 300, text: 'Custom note', color: 'emerald' }
      ]
    };

    const currentEntities: EntityModel[] = [
      {
        id: '1',
        name: 'Application',
        filePath: '/src/Application.cs',
        line: 1,
        projectName: 'App',
        properties: []
      }
    ];

    const synced = liveSyncDiagramWithCode(saved, currentEntities);
    assert.deepEqual(synced, {
      Application: { x: 120, y: 150 }
    });
    assert.equal(saved.notes?.length, 1);
    assert.equal(saved.notes?.[0].color, 'emerald');
  });
});
